# Generated by Django 3.2.25 on 2025-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('command', models.CharField(help_text="e.g., 'python manage.py run_scanner www.google.com'", max_length=255)),
                ('schedule', models.CharField(blank=True, help_text="Cron spec (e.g., '0 0 * * *') or blank for on-demand", max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_run_success', models.BooleanField(editable=False, null=True)),
                ('retries', models.IntegerField(default=0)),
                ('notify_on_error', models.BooleanField(default=True)),
                ('last_run_stdout', models.TextField(blank=True, editable=False, null=True)),
                ('last_run_stderr', models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
