# Generated by Django 3.2.25 on 2025-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.CharField(blank=True, help_text='Container image to run the task (e.g., surface-security:latest)', max_length=255, null=True),
        ),
    ]
